language: python

install: make install-test

cache: pip

script:
  - export PYTHONPATH=`pwd`
  - make lint
  - pytest --vcr-record=none

jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      install:
        - make install-test
        - pip install coveralls
      script:
        - export PYTHONPATH=`pwd`
        - pytest --vcr-record=none
        - coveralls
    - stage: PyPI Upload
      python: 3.7
      dist: xenial
      sudo: true
      script: echo "Uploading packages to PyPI"
      deploy:
        provider: pypi
        user: cuenca
        password:
          secure: "ADBD8QRDQXD/hO3kM/4FJgYoh4fMFwyrFdpPGhnsO5A/ktT/zUKUukiA3pvhecz+mCxCRmYYAKxd/t2c4bnEML1bN7wKHOSsLiMPiIVkY1MQR2pHCVeW0asPrXYZCwJzeGGIGlxw7mRERQLNu/g0DpH7cXxq/8PVGNSCQIvUZbTc5IilkoD0AzeOoGqGV5xXGU54/sC6/FvVYU7n87ycorlX8jPVsb09YAsTn+/wWm4TsvqcdXPl+lAqBZgV0wQ68x8LTuOfuTlcOeCwpwplpaPio4axzfG8HDaEbC2X9EkNrDquOKonIVz8wpo1xgVGpZDTkd6MdQUkjLzqkd1eIG7/amIZC2xL6Z2e9U1ewScGIRcDhyfsXPoc/qNQVdNv9QOWF5lxptUOgp5CjGjbiNePJGOIhG9/xNTKv9VDs5og6vYQQkjNaVno30sZZvwW4VLI09RVET9cq+/5/5YOmUkbtyMaFtA3+fgCTtzu4+7G+ULw7TXpagvVvHZI/IZ/fGZfl+8KwwAV/yvhxqiqeWNoFf/Ehnv+Kj9MXqsG+U2edPEAZDRqv4Ztd+K5LqmI3DRbNw/ubRPXW+4yreff7/oIVeEoUJZtv3AUjIYQP65z/0W05kYeVb2PMdHCGs2YR3ySaskAgAZxZUIQmyMsK7fLgfsI5JmPcjIWRM0vAbE="

        on:
          tags: true
        distributions: sdist bdist_wheel
